### PR TITLE
Update for compat with new poise 2.0 release

### LINKED ISSUE #90: Pin back to poise ~> 1.x or make compatible with 2.x
Seeing some folks report issues with this cookbook, e.g. https://github.com/rackspace-cookbooks/elkstack/issues/149. These seem to boil down to recent changes to poise.

### PR DESCRIPTION
**Pull request by martinb3**
- Add `require 'poise'` to be compatible with [new release of poise](https://github.com/poise/poise/blob/master/CHANGELOG.md#v200) as gem, fixes #90.

### CODE REVIEW

**Comment by EdHurtig** [comment]
:+1:

**Comment by lmunro** [comment]
:+1:

**Comment by BCWilsonDotCom** [comment]
+1 Can we get a merge on this?

**Comment by jujugrrr** [comment]
:+1: , Any news on this one ?

**Comment by martinb3** [comment]
@paulczar or @lusis, I'd be glad to help maintain this if it helps get fixes out faster. Thanks!

**Comment by paulczar** [comment]
merged and pushed to supermarket as `v2.0.5`

**Pull request merged**
